### ISSUE TITLE
Solving a dependency nightmare

### ISSUE THREAD

**Issue by ethernetdan** [redspread/spread#30]
So I've quickly learned that we're going to run into trouble unless we lock our dependencies to the versions required into Kubernetes. The issue first arose because the `image` package relies on a newer version of Docker then Kubernetes is able to build with but this was a long time coming.

I made several attempts at making this happen and ended up in a bit of a mess. My first attempt was to use Godeps (see #21) but I ran into an issue with Kubernetes [not playing well](https://github.com/kubernetes/kubernetes/blob/ed95a6d/pkg/api/mapper.go#L49) with Godep's rewriting of imports. My second attempt was to switch from Godeps to the vendor experiment, this resolved the import check problem with Kubernetes but has left a convoluted commit history. However, I am concerned about the way it was setup.

I am going to rewind back into the commit history and apply this fix. This operation breaks the commit history and leaves dangling PRs so it's something that should absolutely be avoided in the future. 

This is my action plan:
- [x] Backup git on another private repo + locally
- [x] Reset to 6880c044fdffcf39d335b34824e1a95d3291246c (PR #16)
- [x] Branch to dep-fix
- [x] Add implementation of github.com/docker/docker/reference to git index
- [x] Fix development_test.go go spew import
- [x] Fix input/input.go
- [x] Setup GOPATH for Kube and enable alias
- [x] godep restore on kubernetes repo
- [x] go get ./… deps into path 
- [x] Run tests
- [x] Commit as “Prep to version dips: reimplemented some Docker reference methods, fixed wrong spew import, fixed sloppy refactor”
- [x] Run export GO15VENDOREXPERIMENT=1
- [x] godep save ./…
- [x] go get -v to ensure all vendored
- [x] Run tests
- [x] Add travis configuration from original
- [x] Commit as “Versioned dependencies in /vendor (recloses #21, recloses #28)”
- [x] Confirm travis build and recommit until working
- [x] Add command disabling
- [x] Commit as “Added command disabling (recloses #24)”
- [x] DANCE BREAK!
- [x] Force push 6880c044fdffcf39d335b34824e1a95d3291246c to master on Github
- [x] Create and merge PR from dep-fix
